//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpensesAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        public int ExpenseId { get; set; }
        public Nullable<int> ExpenseCatId { get; set; }
        public Nullable<System.DateTime> ExpenseDate { get; set; }
        public Nullable<int> ExpenseCost { get; set; }
        public string Comment { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual ExpenseCategory ExpenseCategory { get; set; }
        public virtual User User { get; set; }
    }
}
